// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title IAASZKVerifier
 * @notice Interface for the AAS ZK proof verifier contract.
 *         Noir circuits compiled with Barretenberg produce UltraHonk proofs.
 *         The real verifier Solidity is auto-generated by `bb write_solidity_verifier`.
 *         This interface wraps that auto-generated contract.
 */
interface IAASZKVerifier {
    /// @notice Verifies a capability threshold proof.
    /// @param proof  Raw UltraHonk proof bytes produced by Barretenberg.
    /// @param publicInputs Public inputs array (taskThreshold, rateThresholdBps).
    /// @return valid True if the proof is valid for the given public inputs.
    function verifyCapabilityProof(
        bytes calldata proof,
        bytes32[] calldata publicInputs
    ) external view returns (bool valid);
}
