import { expect } from "chai";
import { ethers } from "hardhat";
import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";
import { AASZKVerifier, HonkVerifier } from "../typechain-types";
import { SignerWithAddress } from "@nomicfoundation/hardhat-ethers/signers";

/**
 * E2E Integration Tests — Real UltraHonk Proof Verification
 *
 * Generates a real proof with nargo/bb and verifies it on-chain
 * against the auto-generated HonkVerifier contract.
 *
 * Prerequisites:
 *   - `nargo` on PATH
 *   - `bb` on PATH or at ~/.bb/bb
 *   - Circuit compiled: circuits/capability-threshold/target/capability_threshold.json
 *   - VK generated: circuits/capability-threshold/target/vk
 */

const CIRCUIT_DIR = path.resolve(__dirname, "../circuits/capability-threshold");
const TARGET_DIR = path.join(CIRCUIT_DIR, "target");

// ─── Helpers ─────────────────────────────────────────────────────

function findBb(): string {
  try {
    return execSync("which bb", { stdio: "pipe" }).toString().trim();
  } catch {
    const homeBb = path.join(process.env.HOME || "~", ".bb", "bb");
    if (fs.existsSync(homeBb)) return homeBb;
    throw new Error("bb binary not found");
  }
}

function nargoAvailable(): boolean {
  try {
    execSync("which nargo", { stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
}

/**
 * Generate a real UltraHonk proof for known test inputs.
 *
 * Test values:
 *   - task_count = 150, success_count = 143
 *   - preimage = [1, 2, 3, 4]
 *   - threshold_tasks = 100, threshold_rate_bps = 9500
 *   - data_commitment = poseidon2_hash([1,2,3,4]) (computed by circuit)
 */
function generateTestProof(): {
  proofHex: string;
  publicInputs: string[];
} {
  const bb = findBb();

  // Compute poseidon2 commitment for test preimage [1,2,3,4]
  const commitmentHex = computePoseidon2Commitment();

  const proverToml = [
    'task_count = "150"',
    'success_count = "143"',
    'data_commitment_preimage = ["1", "2", "3", "4"]',
    'threshold_tasks = "100"',
    'threshold_rate_bps = "9500"',
    `data_commitment = "${commitmentHex}"`,
  ].join("\n") + "\n";

  fs.writeFileSync(path.join(CIRCUIT_DIR, "Prover.toml"), proverToml);

  // Execute witness
  execSync("nargo execute", { cwd: CIRCUIT_DIR, stdio: "pipe", timeout: 30_000 });

  const witnessPath = path.join(TARGET_DIR, "capability_threshold.gz");
  if (!fs.existsSync(witnessPath)) {
    throw new Error("Witness not found");
  }

  // Generate proof — -o TARGET_DIR writes "proof" and "public_inputs" files there
  const artifactPath = path.join(TARGET_DIR, "capability_threshold.json");
  execSync(
    `${bb} prove --scheme ultra_honk --oracle_hash keccak -b "${artifactPath}" -w "${witnessPath}" -o "${TARGET_DIR}"`,
    { cwd: CIRCUIT_DIR, stdio: "pipe", timeout: 120_000 }
  );

  const proofPath = path.join(TARGET_DIR, "proof");
  if (!fs.existsSync(proofPath)) {
    throw new Error("Proof not generated");
  }

  // Verify locally first
  const vkPath = path.join(TARGET_DIR, "vk");
  execSync(
    `${bb} verify --scheme ultra_honk --oracle_hash keccak -k "${vkPath}" -p "${proofPath}"`,
    { cwd: CIRCUIT_DIR, stdio: "pipe", timeout: 60_000 }
  );

  // Read proof bytes
  const proofBuf = fs.readFileSync(proofPath);
  const proofHex = "0x" + proofBuf.toString("hex");

  // Read public inputs from the binary file generated by bb prove
  const pubInputsBuf = fs.readFileSync(path.join(TARGET_DIR, "public_inputs"));
  const publicInputs: string[] = [];
  for (let i = 0; i < pubInputsBuf.length; i += 32) {
    publicInputs.push("0x" + pubInputsBuf.subarray(i, i + 32).toString("hex"));
  }

  return { proofHex, publicInputs };
}

/**
 * Compute poseidon2_hash([1,2,3,4]) by running a helper circuit.
 * Parses the "Circuit output: Field(...)" line from nargo execute.
 */
function computePoseidon2Commitment(): string {
  const helperDir = path.join(CIRCUIT_DIR, "..", "_commitment_helper");
  const helperSrc = path.join(helperDir, "src");

  try {
    fs.mkdirSync(helperSrc, { recursive: true });

    fs.writeFileSync(
      path.join(helperDir, "Nargo.toml"),
      [
        '[package]',
        'name = "commitment_helper"',
        'type = "bin"',
        'authors = ["AAS"]',
        '',
        '[dependencies]',
      ].join("\n") + "\n"
    );

    fs.writeFileSync(
      path.join(helperSrc, "main.nr"),
      [
        'fn main(preimage: pub [Field; 4]) -> pub Field {',
        '    let result: [Field; 4] = std::hash::poseidon2_permutation(preimage, 4);',
        '    result[0]',
        '}',
      ].join("\n") + "\n"
    );

    fs.writeFileSync(
      path.join(helperDir, "Prover.toml"),
      'preimage = ["1", "2", "3", "4"]\n'
    );

    // Compile and execute — capture stdout for "Circuit output: Field(...)"
    execSync("nargo compile", { cwd: helperDir, stdio: "pipe", timeout: 30_000 });
    const output = execSync("nargo execute", {
      cwd: helperDir,
      encoding: "utf-8",
      timeout: 30_000,
    });

    // Parse: "Circuit output: Field(12345)" or "Circuit output: Field(-12345)"
    const match = output.match(/Circuit output:\s*Field\((-?\d+)\)/);
    if (!match) {
      throw new Error(`Could not parse circuit output: ${output}`);
    }

    const BN254_P = 21888242871839275222246405745257275088548364400416034343698204186575808495617n;
    let value = BigInt(match[1]);
    if (value < 0n) {
      value = BN254_P + value; // convert to canonical form
    }
    return value.toString();
  } finally {
    try {
      fs.rmSync(helperDir, { recursive: true, force: true });
    } catch {
      // ignore cleanup errors
    }
  }
}

// ─── Tests ───────────────────────────────────────────────────────

describe("E2E: UltraHonk Proof Verification", function () {
  // Proof generation can take 30-60s
  this.timeout(180_000);

  let zkVerifier: AASZKVerifier;
  let honkVerifier: HonkVerifier;
  let owner: SignerWithAddress;

  const hasTools = nargoAvailable();

  before(async function () {
    if (!hasTools) {
      console.log("    ⚠ Skipping E2E tests: nargo/bb not available");
      this.skip();
    }

    // Check circuit is compiled
    if (!fs.existsSync(path.join(TARGET_DIR, "capability_threshold.json"))) {
      console.log("    ⚠ Skipping E2E tests: circuit not compiled");
      this.skip();
    }

    [owner] = await ethers.getSigners();

    // Deploy HonkVerifier (auto-generated)
    const HonkVerifierFactory = await ethers.getContractFactory("HonkVerifier");
    honkVerifier = (await HonkVerifierFactory.deploy()) as unknown as HonkVerifier;
    await honkVerifier.waitForDeployment();

    // Deploy AASZKVerifier
    const ZKVerifierFactory = await ethers.getContractFactory("AASZKVerifier");
    zkVerifier = (await ZKVerifierFactory.deploy()) as unknown as AASZKVerifier;
    await zkVerifier.waitForDeployment();

    // Wire them together
    await zkVerifier.setHonkVerifier(await honkVerifier.getAddress());
  });

  it("should generate and verify a real UltraHonk proof on-chain", async function () {
    console.log("    Generating real UltraHonk proof...");
    const { proofHex, publicInputs } = generateTestProof();

    console.log(`    Proof size: ${(proofHex.length - 2) / 2} bytes`);
    console.log(`    Public inputs: ${publicInputs.length}`);

    // Verify via the raw HonkVerifier contract
    const directResult = await honkVerifier.verify(proofHex, publicInputs);
    expect(directResult).to.be.true;

    console.log("    ✓ Direct HonkVerifier.verify() passed");
  });

  it("should verify via AASZKVerifier wrapper", async function () {
    console.log("    Generating real UltraHonk proof...");
    const { proofHex, publicInputs } = generateTestProof();

    // Verify via the AASZKVerifier wrapper
    const wrappedResult = await zkVerifier.verifyCapabilityProof(
      proofHex,
      publicInputs
    );
    expect(wrappedResult).to.be.true;

    console.log("    ✓ AASZKVerifier.verifyCapabilityProof() passed");
  });

  it("should reject a tampered proof", async function () {
    const { proofHex, publicInputs } = generateTestProof();

    // Tamper with the proof: flip a byte near the middle
    const tamperedProof =
      proofHex.slice(0, 100) +
      (proofHex[100] === "a" ? "b" : "a") +
      proofHex.slice(101);

    // The HonkVerifier should revert or return false
    try {
      const result = await honkVerifier.verify(tamperedProof, publicInputs);
      // Some verifiers return false instead of reverting
      expect(result).to.be.false;
    } catch {
      // Verifier reverted — also acceptable behavior
      expect(true).to.be.true;
    }

    console.log("    ✓ Tampered proof correctly rejected");
  });

  it("should reject wrong public inputs", async function () {
    const { proofHex, publicInputs } = generateTestProof();

    // Change the task threshold public input
    const wrongInputs = [...publicInputs];
    wrongInputs[0] = ethers.zeroPadValue(ethers.toBeHex(999), 32);

    try {
      const result = await honkVerifier.verify(proofHex, wrongInputs);
      expect(result).to.be.false;
    } catch {
      // Verifier reverted — also acceptable
      expect(true).to.be.true;
    }

    console.log("    ✓ Wrong public inputs correctly rejected");
  });
});
